// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1 - The Robotic Nervous System',
      items: [{ type: 'autogenerated', dirName: 'Module-1-ROS2' }],
    },
    {
      type: 'category',
      label: 'Module 2 - The Digital Twin',
      items: [{ type: 'autogenerated', dirName: 'Module-2-Simulation' }],
    },
    {
      type: 'category',
      label: 'Module 3 - The AI-Robot Brain',
      items: [{ type: 'autogenerated', dirName: 'Module-3-Nvidia-Isaac' }],
    },
    {
      type: 'category',
      label: 'Module 4 - Vision-Language-Action',
      items: [{ type: 'autogenerated', dirName: 'Module-4-VLA' }],
    },
    {
      type: 'category',
      label: 'Hardware Requirements',
      items: [{ type: 'autogenerated', dirName: 'Hardware' }],
    },
    {
      type: 'category',
      label: 'Curriculum',
      items: [{ type: 'autogenerated', dirName: 'Curriculum' }],
    },
  ],
};

module.exports = sidebars;